### ISSUE TITLE
Getting an error: "gh: Not Found (HTTP 404***" even though the report is successfully publishing

### ISSUE THREAD

**Issue by tking16** [PavanMudigonda/html-reporter-github-pages#14]
The report does seem to be being sent to the repo however the job itself never seems to actually pass. And I don't really understand the error

<img width="1150" alt="Screenshot 2024-11-05 at 10 44 32" src="https://github.com/user-attachments/assets/ee95a213-2f87-44a4-a4f8-abe6d1e4a1ab">

Will post my job below for more context, also the repo I send the report to is a private repository if that is possibly what's causing the issue
```
      - name: Deploy to Github Pages
        if: needs.test.result == 'failure'
        uses: PavanMudigonda/html-reporter-github-pages@v1.3
        with:
          test_results: html-report
          keep_reports: 10
          gh_pages: main # BRANCH NAME
          external_repository: private-org-repo/html-reports
          subfolder: reports  # Level 1 Folder Structure
          tool_name: appium # Level 2 Folder Structure
          workflow_name: android # Level 3 Folder Structure
          env: ${{ github.head_ref }} # Level 4 Folder Structure
          token: ${{ secrets.HTML_REPORT_GH_PAT }}
```

Tiny seperate issue side-note, I think there might a bug with the `GITHUB_PAGES_WEBSITE_URL` variable, as it doesn't seem to include the subfolder argument ("reports" in my case). 

Also this on a Linux machine, thanks for the help!
