### ISSUE TITLE
version 1.3 issue with cd command and a space in Github action anme

### ISSUE THREAD

**Issue by angold5** [PavanMudigonda/html-reporter-github-pages#8]
Hi

I think v1.3 has an issue with spaces in a name. The Github action has a spca ein the name and is called "Pre-merge checks"

```
Run PavanMudigonda/html-reporter-github-pages@43a7b6d494590d2a80a5bf9daf8eba62fae4e3b2
  with:
    test_results: test-reports
    gh_pages: test-reports-history
    results_history: results-history
    keep_reports: 35
    tool_name: test-reports
    workflow_name: Pre-merge checks
    env: QA
    order: descending
    allure_report_generate_flag: false
```

Im not sure why it says "xxxx-1.2" below.

```
 inflating: html-reporter-github-pages-1.2/test-results/trace/index.html  
  inflating: html-reporter-github-pages-1.2/test-results/trace/main.a5d7e729.css  
  inflating: html-reporter-github-pages-1.2/test-results/trace/main.ce7ea3d1.js  
  inflating: html-reporter-github-pages-1.2/test-results/trace/sw.bundle.js  
null
current path: /home/runner/work/devplatform-deploy/devplatform-deploy
NEW results history folder test-reports-history/test-reports/Pre-merge checks/QA
New GH_PAGES folder: test-reports-history/test-reports/Pre-merge checks/QA
NEW github pages url null/test-reports/Pre-merge checks/QA
/home/runner/work/_temp/f0cda3aa-6365-47f2-a055-02450e3c5507.sh: **line 156: cd: too many arguments**
```
